### ISSUE TITLE
Feature request: Ping keep alive

### ISSUE THREAD

**Issue by subatomike** [jpg0/wmp2mqtt#3]
What do you think about adding a periodic ping to keep the TCP connection alive?

**Comment by jpg0** [comment]
I guess that would be fine; do you see periodic disconnects? I haven't experienced any issues, although I'm aware there is code to reconnect if it gets disconnected.

**Comment by subatomike** [comment]
I see 'warn: WMP Connection closed' after idle time. This also matches the statement from their [WMP doc](https://cdn.hms-networks.com/docs/librariesprovider11/manuals-design-guides/wmp-protocol-specifications.pdf?sfvrsn=339b5cd7_6): 

> Intesis devices close the TCP communication if no communication is received during 2 minutes.
To avoid unexpected TCP communication losses with the device, it is highly recommended to
periodically ping the device or demand a value (e.g. ambient temperature) with an appropriate
period of time (30s ≤ t ≤ 1min).

I'm curious why you don't see disconnects. Are you sending queries or commands that keep it alive? Thanks for the response!

**Comment by jpg0** [comment]
My logs are full of changes in AMBTEMP coming from the WMP unit. Possibly that is keeping it alive?

**Comment by subatomike** [comment]
Good question. I also see AMBTEMP updates every time the temperature reading changes by 0.1C. However even with many of them, the connection closes after 2 min of opening (if I don't send anything). I'm no mqtt expert... Are there any differences between brokers such that yours is doing some confirmation, or anything that Intesis might see as activity?

**Comment by jpg0** [comment]
I managed to find a single disconnect in my logs, but it was over a week ago. So not sure what the difference is; my broker is mosquitto, but I can't imagine that making too much difference. I wonder if it's a network topology thing, maybe if the connection is going thru different switches they are creating a difference (also my server is linux, not sure if that has an impact).

As for actually implementing a regular ping - would you be able to do this and submit a PR? I can certainly put it in my list but unfortunately it's not going to be a very high priority.

**Comment by subatomike** [comment]
Ok, I'll try. One last request, could you check the revision or firmware version of your Intesis?

**Comment by jpg0** [comment]
INFO:RUNVERSION,1.0.7
INFO:CFGVERSION,1.0.2
INFO:WLANVERSION:2.0.45
INFO:DEVICEINFO,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
INFO:HASH,0801:0106

**Comment by subatomike** [comment]
For completeness here are mine. Some differences, but not sure what changes are
INFO:RUNVERSION1.3.3
INFO:CFGVERSION,1.2.3
INFO:WLANVERSION,2.0.0
INFO:DEVICEINFO,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
INFO:HASH,0801:0100

**Comment by jpg0** [comment]
A small update: my unit disconnected a few times over the last few days. No idea why. But I see that it leaves this system in a bad state - running and accepting messages but doing nothing.

So what I've changed is to make it gracefully exit when it get's disconnected from the WMP endpoint. At this point it can be restarted, which, if you're using a supervisor like systemd, which happen automatically.

Not sure if this improves the situation for you (I suspect you have moved on to something else), but thought I'd let you know.
